title: Climber Tools
email: tomas@slama.dev
description: >-
  The Climber Tools website.

url: "https://climber.tools"
baseurl: ""

exclude: ["package*.json", "*.js"]

permalink: /:title/

plugins:
  - jekyll-postcss

postcss:
  cache: false
